apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: hkrishnamurthycloud/python-hello-world/.cloudbees/workflows/callable-workflow-1f9d58a6-51fb-4173-8013-7826731ed579.yaml
    