apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
# test comment
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: hkrishnamurthycloud/python-hello-world/.cloudbees/workflows/callable-workflow-eb83655b-64f8-4f06-ad64-30314176a446.yaml
