apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: hkrishnamurthycloud/python-hello-world/.cloudbees/workflows/callable-workflow-8f9851a3-2d32-4c97-92c2-8eda8a0f72a7.yaml
    