apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: hkrishnamurthycloud/python-hello-world/.cloudbees/workflows/callable-workflow-7c78fce2-019e-4941-aa2c-cae5469c6588.yaml
    